spring:
 codec: 
  max-in-memory-size: 300MB
 datasource: 
   url:
   username: 
   password: 
   driver-class-name:

 jpa:
   hibernate:
     ddl-auto: update
   generate-ddl: true
   database-platform: 

external: 
  api:
    auth:
      tokenUrl:
      apiUrl: 
      username: 
      password: 
      tokenExpireBuffer: 60
    leagueId: 
         